### ISSUE TITLE
希望能在下载大文件时加入进度条

### ISSUE THREAD

**Issue by Steve5wutongyu6** [chromiumer/respeed#2]
![image](https://user-images.githubusercontent.com/77491648/224491177-6a097f8a-3e95-4d2c-86e4-5008b7126720.png)
在下载较大文件时会在如图所示界面停留较长时间，在需要批量下载的时候可能会妨碍添加后续下载任务，希望能加入进度条或者将等待界面缩小。

**Comment by chromiumer** [comment]
下载工具本身的定位就是小文件加速，小文件基本是秒下，不适合镜像类的大文件下载，每月流量有限，并且网站运营成本都是自付，没办法支持更多，希望理解。

**Comment by chromiumer** [comment]
> 下载工具本身的定位就是小文件加速，小文件基本是秒下，不适合镜像类的大文件下载，每月流量有限，并且网站运营成本都是自付，没办法支持更多，希望理解。


下载工具本身的定位就是小文件加速，小文件基本是秒下，不适合镜像类的大文件下载，每月流量有限，并且网站运营成本都是自付，没办法支持更多，希望理解。

**Comment by chromiumer** [comment]
> ![image](https://user-images.githubusercontent.com/77491648/224491177-6a097f8a-3e95-4d2c-86e4-5008b7126720.png) 在下载较大文件时会在如图所示界面停留较长时间，在需要批量下载的时候可能会妨碍添加后续下载任务，希望能加入进度条或者将等待界面缩小。


下载工具本身的定位就是小文件加速，小文件基本是秒下，不适合镜像类的大文件下载，每月流量有限，并且网站运营成本都是自付，没办法支持更多，希望理解。

**Comment by Steve5wutongyu6** [comment]
明白了，理解。
