### ISSUE TITLE
SOS

### ISSUE THREAD

**Issue by kaosu1996** [chromiumer/respeed#3]
由于部分原因手机变砖了，之前贪便宜买的京东二手是国外发行版tmobile
现在要下载国外的刷机包；现在任何支付和验证方式都用不了,只有还处在登录状态的github和少部分邮箱能用，所以很急

不好意思违例下载了多次https://ava2.androidfilehost.com/dl/ASIhnOGlz4r_DsMOCfvijA/1690704541/6006931924117886572/guacamole_21.O.09_190516.7z?
这个链接的刷机包，是因为我不知道有没有下载完，因为大文件下载貌似网页会一直读条我不清楚代理服务器下载状态，所以会多次请求下载,麻烦能帮我解决下这个问题吗?
或者搞个读条.....万分抱歉

**Comment by chromiumer** [comment]
试了下文件链接，https://ava2.androidfilehost.com/dl/ASIhnOGlz4r_DsMOCfvijA/1690704541/6006931924117886572/guacamole_21.O.09_190516.7z?
源站做了限速，方便可以留下邮箱，或者在respeed通过邮件沟通。
